---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscache
  labels:
    app: rediscache
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: rediscache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rediscache
    spec:
      containers:
      - name: rediscache
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 0
        envFrom:
        - configMapRef:
            name: rediscache-env
      terminationGracePeriodSeconds: 180